SDMAssignTwo/Models/ErrorViewModel.cs
using System;

namespace SocialDataMiningApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SDMAssignTwo/Models/RedditModel.cs
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SocialDataMiningApp.Models
{
    public class RedditModel
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string _id { get; set; }
        public string post_id { get; set; }
        public string title { get; set; }
        public string post { get; set; }
        public string name { get; set; }
        public int upvotes { get; set; }
        public string subreddit { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

SDMAssignTwo/Models/TwitterModel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace SocialDataMiningApp.Models
{
    public class TwitterModel
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string _id { get; set; }
        public string idStr { get; set; }
        public string text { get; set; }
        public string author { get; set; }
        public int retweetCount { get; set; }
        public string language { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

SDMAssignTwo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using SocialDataMiningApp.Models;

namespace SocialDataMiningApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SDMAssignTwo/Controllers/RedditController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Reddit;
using System;
using System.Threading.Tasks;
using SocialDataMiningApp.Models;
using SocialDataMiningApp.Services;

namespace SocialDataMiningApp.Controllers
{

    public class RedditController : Controller
    {
        private string appId;
        private string refreshToken;
        private string appSecret;
        private string accessToken;
        private readonly RedditService _redditService;

        public RedditController(IConfiguration configuration, RedditService redditService)
        {
            appId = configuration["Authentication:Reddit:appId"];
            refreshToken = configuration["Authentication:Reddit:refreshToken"];
            appSecret = configuration["Authentication:Reddit:appSecret"];
            accessToken = configuration["Authentication:Reddit:accessToken"];
            _redditService = redditService;

        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Send([Bind("title,post")] RedditModel redditModel)
        {
            var reddit = new RedditClient(appId, refreshToken, appSecret, accessToken, "v1");
            var mySub = reddit.Subreddit("sircmpwn");
            var mySelfPost = mySub.SelfPost(redditModel.title, redditModel.post);


            var post = await mySelfPost.SubmitAsync();
            redditModel.name = reddit.Account.Me.Name;
            redditModel.post_id = post.Id;
            redditModel.upvotes = post.UpVotes;
            redditModel.subreddit = post.Subreddit;
            redditModel.CreationDate = DateTime.Now;
            await _redditService.Create(redditModel);
            return View("Confirm");
        }
    }
}

SDMAssignTwo/Controllers/TwitterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SocialDataMiningApp.Models;
using SocialDataMiningApp.Services;
using System;
using System.Net;
using System.Threading.Tasks;
using TweetSharp;

namespace SocialDataMiningApp.Controllers
{
    public class TwitterController : Controller
    {
        private string oAuthConsumerKey = String.Empty;
        private string oAuthConsumerSecret = String.Empty;
        private string accessToken = String.Empty;
        private string accessTokenSecret = String.Empty;

        public IConfiguration Configuration { get; }
        private readonly TwitterModelService _tmService;

        public TwitterController(IConfiguration configuration, TwitterModelService tmService)
        {
            Configuration = configuration;
            oAuthConsumerKey = Configuration["Authentication:Twitter:ConsumerAPIKey"];
            oAuthConsumerSecret = Configuration["Authentication:Twitter:ConsumerSecret"];
            accessToken = Configuration["Authentication:Twitter:ConsumerAccessToken"];
            accessTokenSecret = Configuration["Authentication:Twitter:ConsumerAccessSecret"];
            _tmService = tmService;
        }

        [HttpPost]
        public IActionResult Send([Bind("text")] TwitterModel tweetModel)
        {
            TwitterService service = new TwitterService(oAuthConsumerKey, oAuthConsumerSecret, accessToken, accessTokenSecret);
            var res = service.SendTweet(new SendTweetOptions { Status = tweetModel.text }, async (tweet, response) =>
            {
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    tweetModel.idStr = tweet.IdStr;
                    tweetModel.author = tweet.Author.ScreenName;
                    tweetModel.retweetCount = tweet.RetweetCount;
                    tweetModel.CreationDate = tweet.CreatedDate;
                    tweetModel.language = tweet.Language;
                    Console.WriteLine(tweet.Location);
                    await _tmService.Create(tweetModel);
                }
            });
            res.AsyncWaitHandle.WaitOne();
            return View("Confirm");
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

SDMAssignTwo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .hr_divider {
        position: relative;
        margin-bottom: 20px;
        width: 100%;
        text-align: center;
    }

        .hr_divider span {
            position: absolute;
            top: -11px;
            background: #fff;
            padding: 0 6px;
        }
</style>
<div class="text-center">
    <div class="card">
        <div class="card-body">
            <p class="display-4">Post something...</p>
            <div class="container pt-3">
                <div class="row">
                    <a asp-controller="Twitter" class="btn btn-primary btn-lg btn-block" asp-area="" asp-action="Index">Twitter</a>
                </div>
                <!--<span style="top: 20px; position: relative; background-color: white; padding: 4px;">Or</span>-->
                <div class="hr_divider">
                    <hr />
                    <span>Or</span>
                </div>
                <div class="row">
                    <a asp-controller="Reddit" class="btn btn-danger btn-lg btn-block" asp-area="" asp-action="Index">Reddit</a>
                </div>
            </div>
        </div>
    </div>
</div>

SDMAssignTwo/Views/Reddit/Confirm.cshtml
@{
    ViewData["Title"] = "Confirm";
}
<div class="text-center">
    <h1 class="display-4">Your post has been sent.</h1>
</div>

SDMAssignTwo/Views/Reddit/Index.cshtml
@using SocialDataMiningApp.Models
@model RedditModel
@{
    ViewData["Title"] = "Reddit";
}

<div class="d-flex justify-content-center">
    <div class="card" style="min-width: 600px;">
        <div class="card-body">
            <h5 class="card-title">Post something on reddit...</h5>
            <form asp-action="Send" asp-controller="Reddit" method="post">
                <div class="row pb-2">
                    <input class="form-control pb-2" placeholder="title..." asp-for="title" type="text" />
                </div>
                <div class="row pb-2">
                    <textarea asp-for="post" placeholder="Enter text..." class="form-control" rows="4"
                              aria-label="With textarea"></textarea>
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-danger w-100">Post</button>
                </div>
            </form>

        </div>
    </div>
</div>

SDMAssignTwo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialDataMiningApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Twitter" asp-action="Index">Twitter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reddit" asp-action="Index">Reddit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SocialDataMiningApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SDMAssignTwo/Views/Twitter/Confirm.cshtml
@{
    ViewData["Title"] = "Confirm";
}
<div class="text-center">
    <h1 class="display-4">Your Tweet has been sent.</h1>
</div>

SDMAssignTwo/Views/Twitter/Index.cshtml
@using SocialDataMiningApp.Models
@model TwitterModel
@{
    ViewData["Title"] = "Twitter";
}

<div class="d-flex justify-content-center">
    <div class="card" style="min-width: 600px;">
        <div class="card-body">
            <h5 class="card-title">Tweet Something...</h5>
            <form asp-action="Send" asp-controller="Twitter" method="post">
                <div class="row pb-2">
                    <textarea class="form-control" placeholder="Enter text..." asp-for="text"
                              rows="4" aria-label="With textarea"></textarea>
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-primary w-100">Tweet</button>
                </div>
            </form>

        </div>
    </div>
</div>